//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursoUsuario
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idCurso { get; set; }
        public int idEstatus { get; set; }
        public Boolean factura { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual estatus estatus { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
