//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiante
    {
        public int id { get; set; }
        public string matricula { get; set; }
        public string carrera { get; set; }
        public string nivelEstudios { get; set; }
        public int usuario_id { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
