//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class edcouteq1Entities : DbContext
    {
        public edcouteq1Entities()
            : base("name=edcouteq1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<cursoUsuario> cursoUsuario { get; set; }
        public virtual DbSet<estatus> estatus { get; set; }
        public virtual DbSet<estudiante> estudiante { get; set; }
        public virtual DbSet<modalidad> modalidad { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sexo> sexo { get; set; }
        public virtual DbSet<situacionFiscal> situacionFiscal { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
