//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class situacionFiscal
    {
        public int id { get; set; }
        public string rfc { get; set; }
        public string documento { get; set; }
        public int idUsuario { get; set; }
        public string email { get; set; }
        public string codigoPostal { get; set; }
        public bool activado { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
